"""check after env fix

Revision ID: 52d938928ab7
Revises: 2c481617145c
Create Date: 2025-12-28 08:29:48.004922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d938928ab7'
down_revision: Union[str, None] = '2c481617145c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matrix_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regime', sa.String(length=64), nullable=False),
    sa.Column('list_name', sa.String(length=255), nullable=True),
    sa.Column('item_no', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('usage_criteria_text', sa.Text(), nullable=True),
    sa.Column('tech_criteria_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regime', 'item_no', 'version', name='uq_matrix_rules_regime_itemno_version')
    )
    op.create_index('ix_matrix_rules_regime_itemno', 'matrix_rules', ['regime', 'item_no'], unique=False)
    op.create_table('patents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_number', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('assignee', sa.String(length=512), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('fulltext', sa.Text(), nullable=True),
    sa.Column('ipc_codes_raw', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_publication_number'), 'patents', ['publication_number'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_no', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_case_no'), 'transactions', ['case_no'], unique=True)
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_transaction_id'), 'ai_runs', ['transaction_id'], unique=False)
    op.create_table('patent_usecases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('usecase_text', sa.Text(), nullable=False),
    sa.Column('normalized_usecase_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=32), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patent_usecases_patent', 'patent_usecases', ['patent_id'], unique=False)
    op.create_index(op.f('ix_patent_usecases_patent_id'), 'patent_usecases', ['patent_id'], unique=False)
    op.create_table('transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('item_model', sa.String(length=255), nullable=True),
    sa.Column('spec_text', sa.Text(), nullable=True),
    sa.Column('attachments_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_items_transaction_id'), 'transaction_items', ['transaction_id'], unique=False)
    op.create_table('usage_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('transaction_item_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('risk_tags', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_item_id'], ['transaction_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_requirements_transaction_id'), 'usage_requirements', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_usage_requirements_transaction_item_id'), 'usage_requirements', ['transaction_item_id'], unique=False)
    op.create_index('ix_usage_requirements_tx_source', 'usage_requirements', ['transaction_id', 'source'], unique=False)
    op.create_table('matrix_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_run_id', sa.Integer(), nullable=False),
    sa.Column('usage_requirement_id', sa.Integer(), nullable=False),
    sa.Column('matrix_rule_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_type', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matrix_rule_id'], ['matrix_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usage_requirement_id'], ['usage_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrix_matches_ai_run_id'), 'matrix_matches', ['ai_run_id'], unique=False)
    op.create_index(op.f('ix_matrix_matches_matrix_rule_id'), 'matrix_matches', ['matrix_rule_id'], unique=False)
    op.create_index('ix_matrix_matches_run_rule', 'matrix_matches', ['ai_run_id', 'matrix_rule_id'], unique=False)
    op.create_index(op.f('ix_matrix_matches_usage_requirement_id'), 'matrix_matches', ['usage_requirement_id'], unique=False)
    op.create_table('patent_retrievals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_run_id', sa.Integer(), nullable=False),
    sa.Column('usage_requirement_id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usage_requirement_id'], ['usage_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patent_retrievals_ai_run_id'), 'patent_retrievals', ['ai_run_id'], unique=False)
    op.create_index(op.f('ix_patent_retrievals_patent_id'), 'patent_retrievals', ['patent_id'], unique=False)
    op.create_index('ix_patent_retrievals_run_usage', 'patent_retrievals', ['ai_run_id', 'usage_requirement_id'], unique=False)
    op.create_index(op.f('ix_patent_retrievals_usage_requirement_id'), 'patent_retrievals', ['usage_requirement_id'], unique=False)
    op.create_table('match_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix_match_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matrix_match_id'], ['matrix_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_evidences_matrix_match_id'), 'match_evidences', ['matrix_match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_evidences_matrix_match_id'), table_name='match_evidences')
    op.drop_table('match_evidences')
    op.drop_index(op.f('ix_patent_retrievals_usage_requirement_id'), table_name='patent_retrievals')
    op.drop_index('ix_patent_retrievals_run_usage', table_name='patent_retrievals')
    op.drop_index(op.f('ix_patent_retrievals_patent_id'), table_name='patent_retrievals')
    op.drop_index(op.f('ix_patent_retrievals_ai_run_id'), table_name='patent_retrievals')
    op.drop_table('patent_retrievals')
    op.drop_index(op.f('ix_matrix_matches_usage_requirement_id'), table_name='matrix_matches')
    op.drop_index('ix_matrix_matches_run_rule', table_name='matrix_matches')
    op.drop_index(op.f('ix_matrix_matches_matrix_rule_id'), table_name='matrix_matches')
    op.drop_index(op.f('ix_matrix_matches_ai_run_id'), table_name='matrix_matches')
    op.drop_table('matrix_matches')
    op.drop_index('ix_usage_requirements_tx_source', table_name='usage_requirements')
    op.drop_index(op.f('ix_usage_requirements_transaction_item_id'), table_name='usage_requirements')
    op.drop_index(op.f('ix_usage_requirements_transaction_id'), table_name='usage_requirements')
    op.drop_table('usage_requirements')
    op.drop_index(op.f('ix_transaction_items_transaction_id'), table_name='transaction_items')
    op.drop_table('transaction_items')
    op.drop_index(op.f('ix_patent_usecases_patent_id'), table_name='patent_usecases')
    op.drop_index('ix_patent_usecases_patent', table_name='patent_usecases')
    op.drop_table('patent_usecases')
    op.drop_index(op.f('ix_ai_runs_transaction_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_transactions_case_no'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_patents_publication_number'), table_name='patents')
    op.drop_table('patents')
    op.drop_index('ix_matrix_rules_regime_itemno', table_name='matrix_rules')
    op.drop_table('matrix_rules')
    # ### end Alembic commands ###
